backend:
  name: github
  repo: xueelaine8-rgb/my-export-site
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "text" }
