backend:
  name: github
  repo: 你的GitHub用户名/你的仓库名

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "text" }